/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * TodoList API
 * TodoList 애플리케이션의 REST API입니다.

## 주요 기능
- Todo CRUD 작업
- 페이징 및 필터링
- 검색 기능
- 통계 조회

## 인증
Bearer 토큰을 사용한 세션 기반 인증이 필요합니다. Authorization 헤더에 'Bearer {sessionId}' 형식으로 전달하세요.

## 에러 처리
모든 에러 응답은 다음 형식을 따릅니다:
```json
{
  "success": false,
  "error": "에러 메시지",
  "details": "상세 정보 (선택사항)"
}
```
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTodosStats200ByPriority } from './getApiTodosStats200ByPriority'
import type { GetApiTodosStats200ByCategory } from './getApiTodosStats200ByCategory'

export type GetApiTodosStats200 = {
  /** 전체 Todo 개수 */
  total: number
  /** 완료된 Todo 개수 */
  completed: number
  /** 미완료 Todo 개수 */
  active: number
  /** 완료율 (%) */
  completionRate: number
  /** 우선순위별 Todo 개수 */
  byPriority: GetApiTodosStats200ByPriority
  /** 카테고리별 Todo 개수 */
  byCategory: GetApiTodosStats200ByCategory
  /** 마감일이 지난 Todo 개수 */
  overdue: number
  /** 오늘 마감인 Todo 개수 */
  dueToday: number
  /** 이번 주 마감인 Todo 개수 */
  dueThisWeek: number
}
