/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * TodoList API
 * TodoList 애플리케이션의 REST API입니다.

## 주요 기능
- Todo CRUD 작업
- 페이징 및 필터링
- 검색 기능
- 통계 조회

## 인증
현재 버전에서는 인증이 필요하지 않습니다.

## 에러 처리
모든 에러 응답은 다음 형식을 따릅니다:
```json
{
  "success": false,
  "error": "에러 메시지",
  "details": "상세 정보 (선택사항)"
}
```
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTodosTodos200TodosItem } from './getApiTodosTodos200TodosItem'

export type GetApiTodosTodos200 = {
  /** Todo 목록 */
  todos: GetApiTodosTodos200TodosItem[]
  /** 전체 Todo 개수 */
  total: number
  /** 현재 페이지 번호 */
  currentPage: number
  /** 전체 페이지 수 */
  totalPages: number
  /** 다음 페이지 존재 여부 */
  hasNext: boolean
  /** 이전 페이지 존재 여부 */
  hasPrev: boolean
}
