/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * TodoList API
 * TodoList 애플리케이션의 REST API입니다.

## 주요 기능
- Todo CRUD 작업
- 페이징 및 필터링
- 검색 기능
- 통계 조회

## 인증
Bearer 토큰을 사용한 세션 기반 인증이 필요합니다. Authorization 헤더에 'Bearer {sessionId}' 형식으로 전달하세요.

## 에러 처리
모든 에러 응답은 다음 형식을 따릅니다:
```json
{
  "success": false,
  "error": "에러 메시지",
  "details": "상세 정보 (선택사항)"
}
```
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthTodosFilter } from './getAuthTodosFilter'
import type { GetAuthTodosPriority } from './getAuthTodosPriority'
import type { GetAuthTodosCategory } from './getAuthTodosCategory'
import type { GetAuthTodosStatus } from './getAuthTodosStatus'
import type { GetAuthTodosSortBy } from './getAuthTodosSortBy'
import type { GetAuthTodosSortOrder } from './getAuthTodosSortOrder'

export type GetAuthTodosParams = {
  page?: string
  limit?: string
  filter?: GetAuthTodosFilter
  priority?: GetAuthTodosPriority
  category?: GetAuthTodosCategory
  status?: GetAuthTodosStatus
  search?: string
  sortBy?: GetAuthTodosSortBy
  sortOrder?: GetAuthTodosSortOrder
  dueDateFrom?: string
  dueDateTo?: string
}
