/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * TodoList API
 * TodoList 애플리케이션의 REST API입니다.

## 주요 기능
- Todo CRUD 작업
- 페이징 및 필터링
- 검색 기능
- 통계 조회

## 인증
Bearer 토큰을 사용한 JWT 인증이 필요합니다. Authorization 헤더에 'Bearer {token}' 형식으로 전달하세요.

## 에러 처리
모든 에러 응답은 다음 형식을 따릅니다:
```json
{
  "success": false,
  "error": "에러 메시지",
  "details": "상세 정보 (선택사항)"
}
```
 * OpenAPI spec version: 1.0.0
 */

export type PatchAuthTodosIdToggle500 = {
  /** 요청 성공 여부 */
  success: boolean
  /** 오류 코드 또는 메시지 */
  error: string
  /** 사용자 친화적 오류 메시지 */
  message: string
  /** 상세 오류 정보 (개발용) */
  details?: string
}
