/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * TodoList API
 * TodoList 애플리케이션의 REST API입니다.

## 주요 기능
- Todo CRUD 작업
- 페이징 및 필터링
- 검색 기능
- 통계 조회

## 인증
현재 버전에서는 인증이 필요하지 않습니다.

## 에러 처리
모든 에러 응답은 다음 형식을 따릅니다:
```json
{
  "success": false,
  "error": "에러 메시지",
  "details": "상세 정보 (선택사항)"
}
```
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiTodosBodyPriority } from './postApiTodosBodyPriority'
import type { PostApiTodosBodyCategory } from './postApiTodosBodyCategory'
import type { PostApiTodosBodyStatus } from './postApiTodosBodyStatus'

export type PostApiTodosBody = {
  /**
   * Todo 제목 (1-200자)
   * @minLength 1
   * @maxLength 200
   */
  title: string
  /** Todo 상세 설명 (선택사항) */
  description?: string
  /** 우선순위 (기본값: medium) */
  priority?: PostApiTodosBodyPriority
  /** 카테고리 (기본값: other) */
  category?: PostApiTodosBodyCategory
  /** Todo 상태 (Kanban 뷰용) */
  status?: PostApiTodosBodyStatus
  /** Todo 정렬 순서 (Kanban 뷰용) */
  order?: number
  /** 마감일 (ISO 8601, 선택사항) */
  dueDate?: string
  /** 태그 목록 */
  tags?: string[]
  /** 예상 소요 시간 (분 단위) */
  estimatedMinutes?: number
}
